###
### Contains common comfyui service configuration
### common = shared between both dev and production
###
version: "3.8"
services:
  comfyui_common:
    build: ./
    image: yumeart/comfy:base
    container_name: yumeart-comfyui-worker
